org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
forge_version=21.1.219
forge_version_range=[21,)
loader_version_range=[4,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20

epicfight_version=21.16.1-mc1.21.1-neoforge
epicskills_version=21.3.1-1.21.1
mod_id=omneria
mod_name=Visitors from Omneria
mod_license=MIT
mod_version=20.14.8.0
mod_group_id=net.forixaim
mod_authors=Forixaim
mod_description=
